name: test-work
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: build
       run: echo"build"
  test:
   runs-on: 
   steps:
     - name: test-phase
       run: echo"testing"
  deploy:
   runs-on:
   steps:
     - name: deploy
       run: echo"deploying"
       
